let products = [
    {
        _id: '1',
        name: 'Ash Scattering',
        category: 'options',
        image: '/images/scatter.png',
        price: 1190,
        brand: 'Performance Designs',
        rating: 5,
        numReviews: 44,
        countInStock: 1,
        description:
            'Ash scattering of your loved one. Family and friends are encouraged to watch at the landing zone. Deployment is executed at 6500 ft which is visible from the ground',
    },

    {
        _id: '2',
        name: 'Additional Skydivers',
        category: 'options',
        image: '/images/skydive.jpg',
        price: 200,
        brand: 'Mirage Systems',
        rating: 5,
        numReviews: 56,
        countInStock: 4,
        description: 'Maximum of 4 skydivers in formation',
    },
    {
        _id: '3',
        name: 'Smoke Trails',
        category: 'options',
        image: '/images/smoke.jpg',
        price: 90,
        brand: 'NZ Aerosports',
        rating: 5,
        numReviews: 23,
        countInStock: 4,
        description:
            'Once under canopy, we will pop smoke visible from the ground',
    },
    {
        _id: '4',
        name: 'Memorial Video',
        category: 'options',
        image: '/images/memorial.jpg',
        price: 280,
        brand: 'Fluid Wings',
        rating: 5,
        numReviews: 44,
        countInStock: 1,
        description:
            'Professional edited video with any pictures/memories you would like to include',
    },
    {
        _id: '5',
        name: 'Tandem Skydive',
        category: 'options',
        image: '/images/tandem.jpg',
        price: 590,
        brand: 'Icarus',
        rating: 5,
        numReviews: 44,
        countInStock: 1,
        description:
            'Your loved ones ashes will be secured to your arm and on your signal, one of our employees with deploy the ashes',
    },
    {
        _id: '6',
        name: 'Sunset Jump',
        category: 'options',
        image: '/images/sunset.jpg',
        price: 360,
        brand: 'RoaminHD',
        rating: 5,
        numReviews: 10,
        countInStock: 1,
        description: 'Jump conducted 15 minutes before sunset',
    },
];

module.exports = products;
